### ISSUE TITLE
Usage of ProgressParser

### ISSUE THREAD

**Issue by Simon-the-Sorcerer** [d-k-bo/python-makemkv#1]
Hi,

thx for your nice wrapper. I have a problem with the ProgressParser example. I have a problem with the ProgressParser example. When I run the sample code from the Readme.md:

```python
from makemkv import MakeMKV, ProgressParser

with ProgressParser() as progress:
    makemkv = MakeMKV(0)
    makemkv.mkv(0, '~/Videos/Really Cool Movie (2021)',
                progress_cb=progress.parse_progress)
```

I get the error message `TypeError: mkv() got an unexpected keyword argument 'progress_cb'`

Am I'm missing something?

**Comment by d-k-bo** [comment]
Thank you for pointing this out!
I changed the callback function to be an attribute of `MakeMKV()` and forgot to change the example.
This should work fine:
```python
from makemkv import MakeMKV, ProgressParser

with ProgressParser() as progress:
    makemkv = MakeMKV(0, progress_handler=progress.parse_progress)
    makemkv.mkv(0, '~/Videos/Really Cool Movie (2021)')
```
Alternatively, you can set the callback with something like `makemkv.progress_handler = progress.parse_progress`.
I'll fix the README and the docs soon.

**Comment by Simon-the-Sorcerer** [comment]
Thank you very much for your answer. I will try it as soon as I get to my desktop.

**Comment by Simon-the-Sorcerer** [comment]
Thanks! It's working now.
