### ISSUE TITLE
Option to redirect/surpress stderr

### ISSUE THREAD

**Issue by gregersn** [d-k-bo/python-makemkv#2]
makemkvcon spits out a lot of error messages, I am guessing this is because Popen send them to stdout,
could it be possible to have some way of redirecting this so they either can be handled with a callback, or just surpress them? 

A lot of it is just status that can't be done a lot with.

**Comment by d-k-bo** [comment]
python-makemkv uses python's [`logging`](https://docs.python.org/3/library/logging.html) module. You can use `logging.basicConfig()` to change logging settings like log format, log level (debug, info, warning, error, critical) or log handlers.
To suppress warnings from makemkv, you can also set the log level of makemkv's Logger to "error"

```python
import logging

logging.getLogger("makemkv").setLevel(logging.ERROR)
```
or suppress all messages
```python
logging.getLogger("makemkv").setLevel(logging.CRITICAL)
```

If you think that the log level of a specific message isn't appropriate (there are ~300 different messages, I have not yet met most of them in a real life situation), feel free to point me to its id (the number in parentheses) and I can take a look at it.

**Comment by gregersn** [comment]
Thank you!
Works just like I wanted. Closing the issue, and will report if any specific message causes a problem.
